<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-23T15:02:56-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="2"  errors="0"  time="21.43">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="2"/>
            <property name="failing" value="2"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="50%"/>
            <property name="failRate" value="50%"/>
            <property name="testStartTime" value="Jun 23, 2020 3:02 PM"/>
            <property name="testExecutionTime" value="21.43 s"/>
            <property name="testTotalTime" value="21.43 s"/>
            <property name="commandTime" value="80.46 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D6300000024c2EAA"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7076300001VpsXX"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="81%"/>
            <property name="orgWideCoverage" value="80%"/>
        </properties>
        <testcase name="testCallout" classname="CalloutClassTest" time="0.14">
            <failure message="System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, Contact_Trigger: execution of BeforeInsert

caused by: System.NullPointerException: Attempt to de-reference a null object

Class.Contact_TriggerHandler.updateContactType: line 206, column 1
Trigger.Contact_Trigger: line 53, column 1: []"><![CDATA[Class.CalloutClassTest.testCallout: line 27, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="6.82">
            <failure message="Methods defined as TestMethod do not support Web service callouts"></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="4.57">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="9.91">
        </testcase>
    </testsuite>
</testsuites>
