<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-01T17:20:20-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="1"  errors="0"  time="23.25">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="3"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="75%"/>
            <property name="failRate" value="25%"/>
            <property name="testStartTime" value="Jun 1, 2020 5:20 PM"/>
            <property name="testExecutionTime" value="23.25 s"/>
            <property name="testTotalTime" value="23.25 s"/>
            <property name="commandTime" value="15.83 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D2g0000008aPPEAY"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7072g00000GABFv"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="77%"/>
            <property name="orgWideCoverage" value="63%"/>
        </properties>
        <testcase name="testMethod1" classname="CommTech_ProjectsTriggerTest" time="1.53">
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="5.33">
            <failure message="System.AssertException: Assertion Failed: Expected: false, Actual: true"><![CDATA[Class.Contact_TriggerTest.runTest: line 79, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="7.52">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="8.87">
        </testcase>
    </testsuite>
</testsuites>
