<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-22T12:44:56-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="3" failures="1"  errors="0"  time="21.36">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="3"/>
            <property name="passing" value="2"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="67%"/>
            <property name="failRate" value="33%"/>
            <property name="testStartTime" value="Jun 22, 2020 12:44 PM"/>
            <property name="testExecutionTime" value="21.36 s"/>
            <property name="testTotalTime" value="21.36 s"/>
            <property name="commandTime" value="132.85 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D6300000024c2EAA"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7076300001VoGVN"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="80%"/>
            <property name="orgWideCoverage" value="79%"/>
        </properties>
        <testcase name="runTest" classname="Contact_TriggerTest" time="8.62">
            <failure message="System.AssertException: Assertion Failed: Expected: false, Actual: true"><![CDATA[Class.Contact_TriggerTest.runTest: line 81, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="5.37">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="7.37">
        </testcase>
    </testsuite>
</testsuites>
