<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-02T10:46:51-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="1"  errors="0"  time="18.03">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="3"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="75%"/>
            <property name="failRate" value="25%"/>
            <property name="testStartTime" value="Jun 2, 2020 10:46 AM"/>
            <property name="testExecutionTime" value="18.03 s"/>
            <property name="testTotalTime" value="18.03 s"/>
            <property name="commandTime" value="12.66 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D2g0000008aPPEAY"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7072g00000GAX4E"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="77%"/>
            <property name="orgWideCoverage" value="64%"/>
        </properties>
        <testcase name="testMethod1" classname="CommTech_ProjectsTriggerTest" time="1.03">
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="3.77">
            <failure message="System.AssertException: Assertion Failed: Expected: true, Actual: false"><![CDATA[Class.Contact_TriggerTest.runTest: line 61, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="6.35">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="6.87">
        </testcase>
    </testsuite>
</testsuites>
